"""Compile MGCP intents into Anthropic skill files (~/.claude/skills/).

This is the v2.3 successor to the deleted Phase 8 ``skill_compiler.py``.
Phase 8 compiled lesson *communities* and auto-graduated lessons out of the
active query pool — that hid knowledge from the LLM and degraded reliability,
which is why it was removed in commit ff375bc.

This compiler is designed to avoid that failure mode:

1. **Intents are the source of truth, not skills.** The skill file is a
   downstream artifact of the intent + its linked workflow + the lessons
   linked to each workflow step. The intent_config.json entry stays
   authoritative; recompiling re-derives the skill from the source.

2. **No graduation.** Compiling a skill does NOT remove the intent from the
   routing config, does NOT remove lessons from the active query pool, does
   NOT change any MGCP behavior. The skill is purely additive — it provides
   two new firing channels (slash command + Claude's description matching)
   on top of the MGCP hook gates and LLM intent classification that already
   exist.

3. **Explicit workflow linking.** The compiler walks
   ``intent.linked_workflow`` rather than discovering workflows via semantic
   match at compile time. Same input always produces the same output,
   regardless of embedding model changes or new workflows being added later.

4. **Stale detection.** Skill files include a generated-on timestamp in a
   comment. The web UI compares the timestamp against backing lesson
   ``updated_at`` values and badges stale skills so the user knows when to
   recompile.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from .intent_config import IntentDefinition, load_config
from .persistence import LessonStore


def _user_skills_dir() -> Path:
    return Path.home() / ".claude" / "skills"


def _project_skills_dir(project_path: Path | None = None) -> Path:
    return (project_path or Path.cwd()) / ".claude" / "skills"


def _resolve_skill_path(intent_name: str, scope: str, project_path: Path | None) -> Path:
    """Return the SKILL.md path for the given intent + scope."""
    if scope == "user":
        base = _user_skills_dir()
    elif scope == "project":
        base = _project_skills_dir(project_path)
    else:
        raise ValueError(f"scope must be 'user' or 'project', got {scope!r}")
    return base / intent_name / "SKILL.md"


def _frontmatter(intent: IntentDefinition) -> str:
    return (
        "---\n"
        f"name: {intent.name}\n"
        f"description: {intent.description}\n"
        "---\n"
    )


def _generation_header(intent: IntentDefinition, workflow_id: str | None) -> str:
    """The do-not-edit comment marking this file as machine-generated."""
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    src_parts = [f"intent '{intent.name}'"]
    if workflow_id:
        src_parts.append(f"workflow '{workflow_id}'")
    sources = " + ".join(src_parts)
    return (
        f"<!-- Generated by MGCP skill_compiler on {now} -->\n"
        f"<!-- Source: {sources} in ~/.mgcp/intent_config.json -->\n"
        "<!-- DO NOT EDIT this file directly. Edit the intent (and its linked workflow/lessons) -->\n"
        "<!-- in MGCP, then recompile via compile_intent_to_skill or the /intents page button. -->\n"
    )


def _render_gate_section(intent: IntentDefinition) -> str:
    """If the intent has a hard keyword gate, render it as a STOP preamble."""
    if not intent.gate_message:
        return ""
    return (
        "## Hard rule\n\n"
        f"{intent.gate_message}\n"
    )


def _render_action_section(intent: IntentDefinition) -> str:
    return (
        "## Action template\n\n"
        f"{intent.action}\n"
    )


async def _render_workflow_section(
    workflow_id: str,
    store: LessonStore,
) -> tuple[str, int, int]:
    """Walk a workflow and render its steps + per-step lessons.

    Returns ``(rendered_markdown, step_count, lesson_count)``. The counts are
    used by the MCP tool's response summary so the caller knows how much
    knowledge got inlined.
    """
    workflow = await store.get_workflow(workflow_id)
    if workflow is None:
        return (
            f"## Procedure\n\n"
            f"*(Linked workflow `{workflow_id}` not found in MGCP. "
            f"The intent compiled without procedural steps.)*\n",
            0,
            0,
        )

    lines = [
        "## Procedure",
        "",
        f"From workflow **{workflow.name}** ({workflow.id}): {workflow.description}",
        "",
    ]

    step_count = 0
    lesson_count = 0
    sorted_steps = sorted(workflow.steps, key=lambda s: s.order)

    for step in sorted_steps:
        step_count += 1
        lines.append(f"### Step {step.order}: {step.name}")
        lines.append("")
        lines.append(step.description)
        lines.append("")
        if step.guidance:
            lines.append(step.guidance)
            lines.append("")

        # Inline checklist if present
        if step.checklist:
            lines.append("**Checklist:**")
            for item in step.checklist:
                lines.append(f"- [ ] {item}")
            lines.append("")

        # Inline lessons (sorted by priority: 1=critical first)
        if step.lessons:
            lines.append("**Lessons that apply here:**")
            sorted_lessons = sorted(step.lessons, key=lambda link: link.priority)
            for link in sorted_lessons:
                lesson = await store.get_lesson(link.lesson_id)
                if lesson is None:
                    lines.append(
                        f"- *(missing lesson `{link.lesson_id}` — was it deleted?)*"
                    )
                    continue
                lesson_count += 1
                priority_label = {1: "CRITICAL", 2: "IMPORTANT", 3: "HELPFUL"}.get(
                    link.priority, "HELPFUL"
                )
                # Lesson id (the human-readable slug) + relevance + action
                lines.append(
                    f"- **[{priority_label}] `{lesson.id}`** — {link.relevance}"
                )
                if lesson.action:
                    lines.append(f"  - Action: {lesson.action}")
                if lesson.rationale:
                    lines.append(f"  - Why: {lesson.rationale}")
            lines.append("")

        # Outputs if any
        if step.outputs:
            lines.append("**Expected outputs:**")
            for out in step.outputs:
                lines.append(f"- {out}")
            lines.append("")

    return "\n".join(lines), step_count, lesson_count


@dataclass
class CompileResult:
    """Summary of what compile_intent_to_skill produced.

    Returned to the MCP tool / web API caller so they can show a useful
    confirmation message ("compiled X bytes from Y steps and Z lessons").
    """

    intent_name: str
    skill_path: Path
    bytes_written: int
    workflow_id: str | None
    step_count: int
    lesson_count: int
    has_gate: bool


async def compile_intent_to_skill(
    intent_name: str,
    store: LessonStore,
    scope: str = "user",
    project_path: Path | None = None,
) -> CompileResult:
    """Compile an MGCP intent into a SKILL.md file.

    Walks ``intent → linked_workflow → ordered steps → lessons-per-step``
    and renders all four layers into a single SKILL.md compatible with
    Anthropic's ``~/.claude/skills/`` plugin format.

    Args:
        intent_name: Name of the intent in ``intent_config.json`` to compile.
        store: An initialized LessonStore for fetching workflows and lessons.
        scope: 'user' (writes to ``~/.claude/skills/``) or 'project'
            (writes to ``<project_path>/.claude/skills/``).
        project_path: Required for project scope; defaults to cwd otherwise.

    Returns:
        CompileResult summarizing what was written.

    Raises:
        ValueError: if the intent doesn't exist or scope is invalid.
    """
    config = load_config()
    intent = next((i for i in config.intents if i.name == intent_name), None)
    if intent is None:
        available = ", ".join(i.name for i in config.intents)
        raise ValueError(
            f"Intent '{intent_name}' not found in intent_config.json. "
            f"Available: {available}"
        )

    skill_path = _resolve_skill_path(intent_name, scope, project_path)
    skill_path.parent.mkdir(parents=True, exist_ok=True)

    sections = [
        _frontmatter(intent),
        _generation_header(intent, intent.linked_workflow),
        f"\n# {intent.name}\n",
    ]

    if intent.gate_message:
        sections.append("\n" + _render_gate_section(intent))

    sections.append("\n" + _render_action_section(intent))

    step_count = 0
    lesson_count = 0
    if intent.linked_workflow:
        workflow_md, step_count, lesson_count = await _render_workflow_section(
            intent.linked_workflow, store
        )
        sections.append("\n" + workflow_md)

    if intent.tags:
        sections.append(
            "\n## Categorization\n\n"
            f"Tags: {', '.join(f'`{t}`' for t in intent.tags)}\n"
        )

    body = "".join(sections)
    skill_path.write_text(body, encoding="utf-8")

    return CompileResult(
        intent_name=intent_name,
        skill_path=skill_path,
        bytes_written=len(body.encode("utf-8")),
        workflow_id=intent.linked_workflow,
        step_count=step_count,
        lesson_count=lesson_count,
        has_gate=bool(intent.gate_message),
    )


def find_skill_path(intent_name: str, scope: str = "user", project_path: Path | None = None) -> Path | None:
    """Return the path to a previously-compiled skill, or None if not present.

    Used by the web UI to detect whether an intent has a compiled skill and
    to compute stale-vs-fresh status against backing lesson updated_at.
    """
    path = _resolve_skill_path(intent_name, scope, project_path)
    return path if path.exists() else None


async def is_skill_stale(
    intent_name: str,
    store: LessonStore,
    scope: str = "user",
    project_path: Path | None = None,
) -> bool | None:
    """Return True if the compiled skill is older than any of its sources.

    Returns None if no skill file exists (not stale, just absent).
    Compares the skill file mtime against:
    - The linked workflow's lessons' updated_at (if any)
    - The intent_config.json mtime (since intent edits update the file)
    """
    skill_path = find_skill_path(intent_name, scope, project_path)
    if skill_path is None:
        return None

    skill_mtime = datetime.fromtimestamp(skill_path.stat().st_mtime, UTC)

    # 1. intent_config.json mtime (any intent edit invalidates dependent skills)
    from .intent_config import _config_path

    config_path = _config_path()
    if config_path.exists():
        config_mtime = datetime.fromtimestamp(config_path.stat().st_mtime, UTC)
        if config_mtime > skill_mtime:
            return True

    # 2. backing lessons via the linked workflow
    config = load_config()
    intent = next((i for i in config.intents if i.name == intent_name), None)
    if intent is None or not intent.linked_workflow:
        return False

    workflow = await store.get_workflow(intent.linked_workflow)
    if workflow is None:
        return False

    for step in workflow.steps:
        for link in step.lessons:
            lesson = await store.get_lesson(link.lesson_id)
            if lesson is None:
                continue
            if lesson.last_refined and lesson.last_refined > skill_mtime:
                return True

    return False
