"""Tests for skill_compiler — intent → SKILL.md compilation.

These tests verify the v2.3 successor to the deleted Phase 8 skill compilation.
The key invariants:
- Compiling does NOT modify the source intent or its lessons
- Same input always produces a parseable, well-formed SKILL.md
- Workflow inlining walks intent → workflow → steps → lessons in order
- Missing/deleted workflows and lessons degrade gracefully
- User-scope and project-scope writes go to different paths
"""

import os
import tempfile
from pathlib import Path

import pytest

from mgcp.intent_config import (
    DEFAULT_INTENTS,
    IntentConfig,
    IntentDefinition,
    save_config,
)
from mgcp.models import Lesson, Workflow, WorkflowStep, WorkflowStepLesson
from mgcp.persistence import LessonStore
from mgcp.skill_compiler import (
    CompileResult,
    compile_intent_to_skill,
    find_skill_path,
    is_skill_stale,
)


@pytest.fixture
def isolated_dirs(monkeypatch):
    """Redirect MGCP_DATA_DIR and HOME so tests don't touch real config or skills."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        monkeypatch.setenv("MGCP_DATA_DIR", str(tmp_path / "mgcp"))
        monkeypatch.setenv("HOME", str(tmp_path / "home"))
        # Pydantic uses Path.home() which reads $HOME on POSIX
        (tmp_path / "home").mkdir()
        (tmp_path / "mgcp").mkdir()
        yield tmp_path


@pytest.fixture
def temp_db(isolated_dirs):
    db_path = str(isolated_dirs / "mgcp" / "test.db")
    yield db_path


@pytest.fixture
def seeded_intent_config(isolated_dirs):
    """Write a default intent config to the isolated MGCP_DATA_DIR."""
    config = IntentConfig(version=1, intents=list(DEFAULT_INTENTS))
    save_config(config)
    return config


# ---------------------------------------------------------------------------
# Compilation without a linked workflow (action-only)
# ---------------------------------------------------------------------------


class TestCompileWithoutWorkflow:
    @pytest.mark.asyncio
    async def test_compiles_intent_with_no_linked_workflow(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        """An intent without linked_workflow still produces a valid SKILL.md."""
        store = LessonStore(db_path=temp_db)
        result = await compile_intent_to_skill("session_end", store, scope="user")

        assert isinstance(result, CompileResult)
        assert result.intent_name == "session_end"
        assert result.workflow_id is None
        assert result.step_count == 0
        assert result.lesson_count == 0
        assert result.has_gate is True  # session_end has a keyword gate
        assert result.skill_path.exists()
        assert result.bytes_written > 0

    @pytest.mark.asyncio
    async def test_skill_file_has_required_frontmatter(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        result = await compile_intent_to_skill("session_end", store, scope="user")
        body = result.skill_path.read_text()

        assert body.startswith("---\n")
        assert "name: session_end" in body
        assert "description:" in body
        assert "---\n" in body[4:]  # closing frontmatter delimiter

    @pytest.mark.asyncio
    async def test_skill_file_has_generation_header(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        """The do-not-edit comment must be present."""
        store = LessonStore(db_path=temp_db)
        result = await compile_intent_to_skill("git_operation", store, scope="user")
        body = result.skill_path.read_text()

        assert "Generated by MGCP skill_compiler" in body
        assert "DO NOT EDIT" in body
        assert "intent 'git_operation'" in body

    @pytest.mark.asyncio
    async def test_gate_message_renders_as_hard_rule(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        result = await compile_intent_to_skill("git_operation", store, scope="user")
        body = result.skill_path.read_text()

        assert "## Hard rule" in body
        assert "STOP" in body or "git rules" in body


# ---------------------------------------------------------------------------
# Compilation WITH a linked workflow (the full chain)
# ---------------------------------------------------------------------------


class TestCompileWithWorkflow:
    @pytest.mark.asyncio
    async def test_compiles_full_chain(self, isolated_dirs, temp_db):
        """Add an intent with linked_workflow → workflow with steps → lessons.
        Then compile and verify everything got inlined."""
        store = LessonStore(db_path=temp_db)

        # Seed two lessons that the workflow steps will reference
        await store.add_lesson(Lesson(
            id="run-linter",
            trigger="commit, push",
            action="Run ruff check src/ tests/ before committing.",
            rationale="Pushing lint errors wastes CI time.",
            tags=["git", "linting"],
        ))
        await store.add_lesson(Lesson(
            id="run-tests",
            trigger="commit, push",
            action="Run pytest -m 'not slow' before pushing.",
            rationale="CI failures after push are avoidable.",
            tags=["git", "testing"],
        ))

        # Build a 2-step workflow that links those lessons
        workflow = Workflow(
            id="pre-commit-discipline",
            name="Pre-commit Discipline",
            description="Verification steps before any git commit",
            trigger="commit, push",
            steps=[
                WorkflowStep(
                    id="lint",
                    name="Lint",
                    description="Run the linter to catch style violations",
                    order=1,
                    lessons=[
                        WorkflowStepLesson(
                            lesson_id="run-linter",
                            relevance="Linter must pass before commit",
                            priority=1,
                        ),
                    ],
                ),
                WorkflowStep(
                    id="test",
                    name="Test",
                    description="Run the test suite",
                    order=2,
                    lessons=[
                        WorkflowStepLesson(
                            lesson_id="run-tests",
                            relevance="Tests must pass before push",
                            priority=1,
                        ),
                    ],
                ),
            ],
        )
        await store.save_workflow(workflow)

        # Build an intent that links to the workflow
        intent = IntentDefinition(
            name="custom_git_op",
            description="commit, push, ship",
            action="Run pre-commit discipline before any git command",
            tags=["git"],
            linked_workflow="pre-commit-discipline",
        )
        save_config(IntentConfig(version=1, intents=[intent]))

        result = await compile_intent_to_skill("custom_git_op", store, scope="user")

        assert result.workflow_id == "pre-commit-discipline"
        assert result.step_count == 2
        assert result.lesson_count == 2

        body = result.skill_path.read_text()
        # Workflow header
        assert "Pre-commit Discipline" in body
        # Step headers in order
        lint_idx = body.find("Step 1: Lint")
        test_idx = body.find("Step 2: Test")
        assert lint_idx > 0
        assert test_idx > lint_idx, "Steps should appear in order"
        # Lesson actions inlined
        assert "Run ruff check" in body
        assert "Run pytest" in body
        # Lesson rationale (Why) inlined
        assert "wastes CI time" in body
        # Priority labels rendered
        assert "CRITICAL" in body

    @pytest.mark.asyncio
    async def test_missing_workflow_degrades_gracefully(
        self, isolated_dirs, temp_db
    ):
        store = LessonStore(db_path=temp_db)
        intent = IntentDefinition(
            name="orphan_intent",
            description="trigger phrase",
            action="do the thing",
            linked_workflow="nonexistent-workflow",
        )
        save_config(IntentConfig(version=1, intents=[intent]))

        result = await compile_intent_to_skill("orphan_intent", store, scope="user")
        assert result.step_count == 0
        assert result.lesson_count == 0
        body = result.skill_path.read_text()
        assert "not found" in body  # the graceful fallback message

    @pytest.mark.asyncio
    async def test_missing_lesson_degrades_gracefully(self, isolated_dirs, temp_db):
        store = LessonStore(db_path=temp_db)
        # Workflow references a lesson that doesn't exist
        workflow = Workflow(
            id="wf-missing-lesson",
            name="Missing Lesson WF",
            description="Tests handling of dangling lesson references",
            trigger="test",
            steps=[
                WorkflowStep(
                    id="step1",
                    name="Step",
                    description="A step",
                    order=1,
                    lessons=[
                        WorkflowStepLesson(
                            lesson_id="lesson-that-doesnt-exist",
                            relevance="N/A",
                            priority=1,
                        ),
                    ],
                ),
            ],
        )
        await store.save_workflow(workflow)
        intent = IntentDefinition(
            name="dangling_intent",
            description="x",
            action="y",
            linked_workflow="wf-missing-lesson",
        )
        save_config(IntentConfig(version=1, intents=[intent]))

        result = await compile_intent_to_skill("dangling_intent", store, scope="user")
        assert result.step_count == 1
        assert result.lesson_count == 0  # the dangling lesson doesn't count
        body = result.skill_path.read_text()
        assert "missing lesson" in body  # the graceful fallback


# ---------------------------------------------------------------------------
# Scope handling
# ---------------------------------------------------------------------------


class TestScopes:
    @pytest.mark.asyncio
    async def test_user_scope_writes_to_home(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        result = await compile_intent_to_skill("session_end", store, scope="user")
        # Path should be under the isolated HOME
        assert str(result.skill_path).startswith(os.environ["HOME"])
        assert ".claude/skills/session_end/SKILL.md" in str(result.skill_path)

    @pytest.mark.asyncio
    async def test_project_scope_writes_to_project_path(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        project_root = isolated_dirs / "fake-project"
        project_root.mkdir()
        result = await compile_intent_to_skill(
            "session_end", store, scope="project", project_path=project_root
        )
        assert str(result.skill_path).startswith(str(project_root))
        assert ".claude/skills/session_end/SKILL.md" in str(result.skill_path)

    @pytest.mark.asyncio
    async def test_invalid_scope_raises(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        with pytest.raises(ValueError, match="scope must be"):
            await compile_intent_to_skill("session_end", store, scope="globally")

    @pytest.mark.asyncio
    async def test_unknown_intent_raises(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        with pytest.raises(ValueError, match="not found"):
            await compile_intent_to_skill("nonexistent_intent", store, scope="user")


# ---------------------------------------------------------------------------
# find_skill_path and is_skill_stale
# ---------------------------------------------------------------------------


class TestSkillLookup:
    @pytest.mark.asyncio
    async def test_find_skill_path_returns_none_when_absent(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        path = find_skill_path("session_end", scope="user")
        assert path is None

    @pytest.mark.asyncio
    async def test_find_skill_path_returns_path_after_compile(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        await compile_intent_to_skill("session_end", store, scope="user")
        path = find_skill_path("session_end", scope="user")
        assert path is not None
        assert path.exists()

    @pytest.mark.asyncio
    async def test_is_skill_stale_returns_none_when_absent(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        result = await is_skill_stale("session_end", store, scope="user")
        assert result is None  # not "stale", just absent

    @pytest.mark.asyncio
    async def test_recompile_overwrites_cleanly(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        store = LessonStore(db_path=temp_db)
        first = await compile_intent_to_skill("session_end", store, scope="user")
        first_size = first.bytes_written
        # Recompile
        second = await compile_intent_to_skill("session_end", store, scope="user")
        # Same path, similar size (timestamp may shift a few bytes)
        assert first.skill_path == second.skill_path
        assert abs(first_size - second.bytes_written) < 100


# ---------------------------------------------------------------------------
# The compile-does-not-modify-source invariant (anti-Phase-8)
# ---------------------------------------------------------------------------


class TestImmutability:
    @pytest.mark.asyncio
    async def test_compile_does_not_remove_intent_from_config(
        self, isolated_dirs, temp_db, seeded_intent_config
    ):
        """The whole point of v2.3: compiling a skill must NOT remove the
        source intent from intent_config.json. Phase 8's failure was hiding
        knowledge from active query — this test enforces that we don't."""
        store = LessonStore(db_path=temp_db)
        from mgcp.intent_config import load_config

        before = {i.name for i in load_config().intents}
        await compile_intent_to_skill("session_end", store, scope="user")
        after = {i.name for i in load_config().intents}
        assert before == after
        assert "session_end" in after

    @pytest.mark.asyncio
    async def test_compile_does_not_remove_lessons(self, isolated_dirs, temp_db):
        """Same invariant for lessons: backing lessons stay queryable."""
        store = LessonStore(db_path=temp_db)
        await store.add_lesson(Lesson(
            id="must-stay-queryable",
            trigger="x",
            action="y",
            rationale="z",
            tags=["test"],
        ))
        workflow = Workflow(
            id="wf",
            name="WF",
            description="d",
            trigger="t",
            steps=[
                WorkflowStep(
                    id="s",
                    name="S",
                    description="d",
                    order=1,
                    lessons=[
                        WorkflowStepLesson(
                            lesson_id="must-stay-queryable",
                            relevance="r",
                            priority=1,
                        ),
                    ],
                ),
            ],
        )
        await store.save_workflow(workflow)
        intent = IntentDefinition(
            name="i",
            description="d",
            action="a",
            linked_workflow="wf",
        )
        save_config(IntentConfig(version=1, intents=[intent]))

        await compile_intent_to_skill("i", store, scope="user")

        # The lesson must still be retrievable via get_lesson
        lesson = await store.get_lesson("must-stay-queryable")
        assert lesson is not None
        assert lesson.id == "must-stay-queryable"
